spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    generate-ddl: off
    database: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/mansShop-test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

server:
  port: 8084

logging:
  file:
    path: logback-spring-integration-test